"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.12.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import tempfile
from pathlib import Path
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-xxz11lmqv6leq2xsu1375^vez)y1-#)4oz@))j=*cj@0a^p5r='

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1', 'localhost', 'testserver']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'ocr',
    'lab',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        # The repo directory is read-only for deletions, which SQLite needs for
        # journal files. Point the database to a temp folder we can freely
        # read/write/delete in.
        'NAME': Path(tempfile.gettempdir()) / 'colohacks_db.sqlite3',
        'OPTIONS': {
            'timeout': 20,
        }
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_METHODS = [
    'GET',
    'POST',
    'PUT',
    'PATCH',
    'DELETE',
    'OPTIONS',
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

DEFAULT_TESSERACT_PATH = Path(r'C:\Program Files\Tesseract-OCR\tesseract.exe')
TESSERACT_CMD = str(DEFAULT_TESSERACT_PATH) if DEFAULT_TESSERACT_PATH.exists() else None
OPENAI_API_KEY = os.getenv('OPENAI_API_KEY', '')
OPENAI_EXTRACTION_MODEL = os.getenv('OPENAI_EXTRACTION_MODEL', 'gpt-4.1-mini')
GEMINI_API_KEY = os.getenv('GEMINI_API_KEY', '')
GEMINI_EXTRACTION_MODEL = os.getenv('GEMINI_EXTRACTION_MODEL', 'gemini-2.5-flash')
OLLAMA_BASE_URL = os.getenv('OLLAMA_BASE_URL', 'http://127.0.0.1:11434')
OLLAMA_EXTRACTION_MODEL = os.getenv('OLLAMA_EXTRACTION_MODEL', 'llava-llama3')
OLLAMA_MINICPM_MODEL = os.getenv('OLLAMA_MINICPM_MODEL', 'openbmb/minicpm-v4.5:8b')
OLLAMA_MOONDREAM_MODEL = os.getenv('OLLAMA_MOONDREAM_MODEL', 'moondream:latest')
OLLAMA_REQUEST_TIMEOUT = int(os.getenv('OLLAMA_REQUEST_TIMEOUT', '420'))
HF_API_KEY = os.getenv('HF_API_KEY', '')
FEATHERLESS_API_KEY = os.getenv('FEATHERLESS_API_KEY', '')
FEATHERLESS_EXTRACTION_MODEL = os.getenv('FEATHERLESS_EXTRACTION_MODEL', 'mistralai/Mistral-7B-Instruct-v0.2')
FEATHERLESS_MAX_PROMPT_CHARS = int(os.getenv('FEATHERLESS_MAX_PROMPT_CHARS', '3000'))
FEATHERLESS_MAX_COMPLETION_TOKENS = int(os.getenv('FEATHERLESS_MAX_COMPLETION_TOKENS', '256'))
