# Generated by Django 5.2.12 on 2026-03-28 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='panform49a',
            name='phone_area_code',
        ),
        migrations.AddField(
            model_name='panform49a',
            name='ao_code_area',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='panform49a',
            name='ao_code_number',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='panform49a',
            name='ao_code_range',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='panform49a',
            name='ao_code_type',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='panform49a',
            name='phone_std_code',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='panform49a',
            name='single_parent_mother_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='panform49a',
            name='title',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='voteridform6',
            name='assembly_constituency',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='voteridform6',
            name='disability_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='voteridform6',
            name='disability_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='voteridform6',
            name='family_epic_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='voteridform6',
            name='place_of_birth_district',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='voteridform6',
            name='place_of_birth_state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='voteridform6',
            name='place_of_birth_town',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='voteridform6',
            name='residence_since',
            field=models.DateField(blank=True, null=True),
        ),
    ]
