# Generated by Django 5.2.12 on 2026-03-28 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0002_remove_panform49a_phone_area_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractionMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('provider', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_visible', models.BooleanField(default=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('supports_images', models.BooleanField(default=True)),
                ('supports_checkboxes', models.BooleanField(default=False)),
                ('requires_api_key', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='panform49a',
            name='extraction_method',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='voteridform6',
            name='extraction_method',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
